trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: taskapi

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release'

- script: |
    docker build -t $(imageName) .
  displayName: Build Docker Image